# Loading libraries
```{r, setup}
library(ggtree)
library(ggtreeExtra)
library(ggplot2)
library(gggenes)
library(tidyverse)
library(data.table)
library(tidytree)
library(ggnewscale)
library(stringr)
library(phangorn)
`%ni%` <- Negate(`%in%`)
library(RColorBrewer)
display.brewer.all(colorblindFriendly = TRUE)
```

# Gene arrow function
```{r}

# Function which plots all the selected gene clusters (every gene cluster in an order for example)
# The function takes a subset size as input, which is the number of gene clusters to plot in each plot
plot_gene_clusters <- function(data, subset_size, ncol = 2, legend_position = "right") {
  # Get the unique regions
  unique_regions <- unique(data$region_id)
  
  # Calculate the number of subsets
  num_subsets <- ceiling(length(unique_regions) / subset_size)
  
  # Loop over each subset
  for(i in seq_len(num_subsets)) {
    # Calculate the indices for this subset
    start_index <- ((i - 1) * subset_size) + 1
    end_index <- min(i * subset_size, length(unique_regions))
    
    # Get the regions for this subset
    subset_regions <- unique_regions[start_index:end_index]
    
    # Filter the data for these regions and plot
    plot <- data %>%
      mutate(strand = ifelse(strand == 1, TRUE, FALSE)) %>%
      filter(region_id %in% subset_regions) %>%
      ggplot(aes(xmin = start, xmax = end, 
      y = product, 
      fill = Query, forward = strand)) +
      geom_gene_arrow() +
      facet_wrap(~ region_id, scales = "free", ncol = ncol) +
      ggtitle(paste("Gene clusters from subset", i, "of", num_subsets)) +
      theme(legend.position = legend_position)
    print(plot)
  }
}

```
# Load GOMC BGCs for pel/pel-like cluster
```{r}

gene_functions <- fread("data/gene_functions.tsv")

taxonomy <- fread("data/GTDB220_HumGut_GOMC/gtdbtk-v2.4.0_GOMC-HumGut.summary.tsv") %>% rename(genome_id = user_genome, gtdb_classification = classification)

# Selected values
selected_values <- fread("data/GOMC/identifiers_pel_pel-like.tsv", header = FALSE)
  
  
data <- fread(
    "data/GOMC/gene_info.tsv") %>%
    mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
    group_by(gene_id) %>%
    ungroup() %>%
    mutate(
        region_id = paste0(genome_id, "_", contig_id, "_", region_id),
        record = gsub("_ASM.*", "", genome_id),
        location = as.character(location),
        location = gsub(":", "_", location),
        location = gsub("]", "_", location),
        location = gsub("\\[", "", location),
        location = gsub(">", "", location),
        location = gsub("<", "", location),
        id = gsub("_genomic", "", genome_id),
        region_id = gsub("_region", ".region", region_id),
        Query = ifelse(str_detect(Query, "pel"), Query, "Other")
    ) %>%
    filter(region_id %in% selected_values$V1) %>%
    separate(`location`, c("start", "end", "strand"), sep = "_") %>%
    mutate(
        start = as.numeric(start),
        end = as.numeric(end),
        strand = ifelse(strand == "(+)", 1, -1)
    ) %>%
    left_join(gene_functions, by = c("Query" = "Query")) %>%
    left_join(taxonomy)


```
# Visualise pel/pel-like clusters
```{r}
plot_gene_clusters(data %>% filter(str_detect(gtdb_classification, "Campylobacterales")), subset_size = 11)


```





