```{r setup, include=FALSE}
library(tidyverse)
library(igraph)
library(stringr)
library(ggforce)
library(data.table)
library(ggupset)
library(gggenes)
library(forcats)
library(ape)
library(RColorBrewer)
library(svglite)
library(aplot)
library(ggh4x) 
library(treeio)
library(ggtree)
library(ggtreeExtra)
library(readxl)
library(ggtext)
`%ni%` <- Negate(`%in%`)
```

## Genomes of interest  - HQ and species-representative
```{r}
# Read supplementary file from MiDAS Global study (must be added to directory)
MiDAS_HQ_tax <- fread("data/MiDAS/22K-hqMAGs.GTDB_midas.taxa.tsv") %>%
  select(genome_id = bin, gtdb_classification = tax_gtdb.r220, MiDAS_classification = "tax_midas_v5.3")

# List of dereplicated MiDAS genomes
MiDAS_derep <- fread("data/MiDAS/derep_MAGs_list.tsv")

# Taxonomy of all dereplicated MiDAS global MAGs
MiDAS_tax_derep_HQ <- MiDAS_HQ_tax %>% filter(genome_id %in% MiDAS_derep$genome_id) %>% select(genome_id, gtdb_classification, MiDAS_classification) %>% mutate(MAG_status = "HQ")


```


```{r}

####################################################################
# Load in MiDAS Global epsSMASH results, add taxonomy and metadata #
####################################################################


MiDAS_all_regions <- fread("data/MiDAS/all_regions.tsv") %>%
  rename(genome_id = file) %>%
  separate_longer_delim(product, delim = " / ") %>%
  mutate(
    Category = ifelse(
      str_detect(product,
        "putative_wzy_dependent|putative_wzy_dependent_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "putative_ABC_dependent|putative_ABC_dependent_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "putative_ABC_or_wzy_dependent"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructansucrase|alpha-glucansucrase"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    ),
    product = case_when(
      product == "acetylated-cellulose" ~ "cellulose-acetylated",
      product == "type-1-cellulose" ~ "cellulose-type-1",
      product == "type-2-cellulose" ~ "cellulose-type-2",
      product == "type-3-cellulose" ~ "cellulose-type-3",
      product == "generic-cellulose" ~"cellulose-generic",
      .default = product
    )
    ) %>% left_join(MiDAS_tax_derep_HQ, by = c("genome_id")) 


MiDAS_tax_w_regions <- MiDAS_tax_derep_HQ %>% full_join(MiDAS_all_regions %>% select(genome_id, product))

```

```{r}
# Read supplementary file from MiDAS 4 study (must be added to directory)
MiDAS_strict <- read_excel("data/MiDAS/midas4_core.xlsx") %>% 
  filter(Best == "Strict core") %>%
  mutate(Genus = ifelse(Genus == "Dechloromonas", "Azonexus", Genus))

MiDAS_tax_Genome_no <- MiDAS_tax_derep_HQ %>%
  separate(MiDAS_classification, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ",[a-z]:") %>%
    mutate(
    Genus = ifelse(
      str_detect(Genus, paste(MiDAS_strict$Genus, collapse = "|")), Genus, "Other Genera"
    ),
    Genus = ifelse(
      str_detect(Genus, "midas_g_81") & Genus != "midas_g_81", "Other Genera", Genus
      ),
    Genus = ifelse(is.na(Genus), "Other Genera", Genus)
    )  %>%
  group_by(Genus) %>%
  mutate(Genus_no = sum(length(Genus))) %>%
  select(Genus, Genus_no) %>% distinct(Genus, .keep_all = TRUE)
  

MiDAS_all_regions_prevalent <- MiDAS_all_regions %>% 
  mutate(
    Category = ifelse(str_detect(product, "-like"), "Synthase (relaxed)", Category)
  ) %>%
  filter(!is.na(MiDAS_classification)) %>%
  separate(MiDAS_classification, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ",[a-z]:") %>%
    mutate(
    Genus = ifelse(
      str_detect(Genus, paste(MiDAS_strict$Genus, collapse = "|")), Genus, "Other Genera"
    ),
    Genus = ifelse(
      str_detect(Genus, "midas_g_81") & Genus != "midas_g_81", "Other Genera", Genus
      ),
    Genus = ifelse(is.na(Genus), "Other Genera", Genus)
    )  %>%
  left_join(MiDAS_tax_Genome_no, by = c("Genus")) %>%
  select(genome_id, Phylum, Family, Genus, Genus_no, product, Category, n_Category, gtdb_classification) %>%
  mutate(
    product = ifelse(Category == "Uncharacterised", "Uncharacterised", product),
    Category = ifelse(Category == "Uncharacterised", "", Category),
    Genus = ifelse(Genus == "Other Genera", "Other Genera", Genus)
         ) %>%
  group_by(genome_id) %>%
  distinct(product, .keep_all = TRUE) %>% 
  ungroup() %>%
  group_by(Genus, n_Category, product) %>%
  mutate(Hits = sum(length(product))) %>% ungroup() %>%
  group_by(Genus) %>%
  distinct(product, .keep_all = TRUE) %>%
  mutate(
    `% genomes with BGC` = round((Hits/Genus_no)*100, digits = 2),
    new_label = ifelse(
      Genus != "Other Genera", 
      paste0(Phylum, " ", Genus, " (", as.character(Genus_no), ")"), 
      paste0(Genus, " (", as.character(Genus_no), ")")
      )
    ) %>% ungroup() %>%
  mutate(
    product = case_when(
      product == "alginate" ~ "Alginate",
      product == "cellulose-acetylated" ~ "tAcetylated cellulose", # t to order it with the other cellulose Types, delete in inkscape
      product == "cellulose-generic" ~ "tGeneric cellulose",
      product == "cellulose-type-1" ~ "Type 1 cellulose",
      product == "cellulose-type-2" ~ "Type 2 cellulose",
      product == "cellulose-type-3" ~ "Type 3 cellulose",
      product == "pel" ~ "Pel",
      product == "pel-positive" ~ "Pel (Gram-positive)",
      product == "PNAG-pga" ~ "PNAG (*pga*)",
      product == "alginate-like" ~ "Alginate-like",
      product == "cellulose-gram-positive-like" ~ "Gram-positive cellulose-like",
      product == "cellulose-like" ~ "Cellulose-like",
      product == "curdlan-like" ~ "Curdlan-like",
      product == "pel-like" ~ "Pel-like",
      product == "PNAG-pga-like" ~ "PNAG (*pga*)-like",
      product == "galactoglucan" ~ "Galactoglucan",
      product == "lactobacillus_eps" ~ "*Lactobacillus* EPS",
      product == "psl" ~ "Psl",
      product == "zooglan" ~ "Zooglan",
      product == "alpha-glucansucrase" ~ "Alpha-glucansucrase",
      product == "fructansucrase" ~ "Fructansucrase",
      product == "Uncharacterised" ~ "Uncharacterised"
      )
  )
  


MiDAS_strict_accessions <- MiDAS_all_regions_prevalent %>%
  separate(gtdb_classification, into = c("GTDB_Domain", "GTDB_Phylum", "GTDB_Class", "GTDB_Order", "GTDB_Family", "GTDB_Genus", "GTDB_Species"), sep = ";[a-z]__") %>%
  distinct(Genus, .keep_all = TRUE)

fwrite(MiDAS_strict_accessions %>% select(genome_id), "data/MiDAS/heatmap_tree_genomes.tsv", sep = "\t")


tree <- read.tree("/home/bio.aau.dk/zs85xk/projects/epsSMASH/epsSMASH_paper/data/MiDAS/tree_heatmap/gtdbtk/classify/gtdbtk.backbone.bac120.classify.tree")



# Select all tips which should not be kept
tree_tib_reduced <- as_tibble(tree) %>%
  filter(!str_detect(label, "\\.bin\\."))

# Remove all tips that are not part of the 15 strict core genomes used to construct the tree
tree_reduced <- drop.tip(tree, tree_tib_reduced$label)

tree_reduced_renamed <- as_tibble(tree_reduced) %>% 
  left_join(MiDAS_strict_accessions %>% select(label = genome_id, new_label)) %>%
  mutate(label = ifelse(str_detect(label, "\\.bin\\."), new_label, label)) %>%
  select(parent,node,branch.length,label)
  
tree_final <- as.phylo(tree_reduced_renamed)


tree_plot <- ggtree(tree_final, layout = "rectangular", branch.length = "none") + xlim_tree(0.1)


MiDAS_heatmap <- ggplot(MiDAS_all_regions_prevalent, aes(fct_reorder(product, n_Category), new_label, fill = `% genomes with BGC`), color = "black") +
  geom_tile(aes(), color = "black") +
  ylab("") +
  scale_fill_gradientn(colors =c("white", "red"), trans = "identity", limits = c(0, 100)) +
  geom_text(aes(label = `% genomes with BGC`), color = "black", size = 5) +
  facet_nested(~ fct_reorder(Category, n_Category), nest_line = element_line(colour = "red"), space = "free", scales = "free_x") +
  theme(
    axis.text.x = element_markdown(angle = 45, hjust = 1, size = 16),
    axis.text.y = element_text(size = 16),
    axis.title.x = element_blank(),
    strip.text = element_text(size = 20)
    ) 

MiDAS_heatmap_tree <- MiDAS_heatmap %>% insert_left(tree_plot, width = 0.1)

MiDAS_heatmap_tree

ggsave("figures/all/Fig4.svg", MiDAS_heatmap_tree, width = 24, height = 16, dpi = 200)

```

