```{r setup, include=FALSE}
library(tidyverse)
library(igraph)
library(stringr)
library(ggforce)
library(data.table)
library(ggupset)
library(gggenes)
library(forcats)
library(readxl)
library(ggfittext)
`%ni%` <- Negate(`%in%`)
```

```{r}
# Read supplementary file from Dueholm et al. study (must be added to directory)
Dueholm_BGCs <- fread("data/Dueholm/Dueholm.tsv") %>% 
  group_by(MAG, Exopolysaccharide) %>% 
  mutate(
    Exopolysaccharide = case_when(
      str_detect(Exopolysaccharide, "Cellulose") ~ "Cellulose",
      Exopolysaccharide == "PNAG_pga" ~ "PNAG (pga)",
      Exopolysaccharide == "PNAG_eps" ~ "PNAG (eps)",
      .default = Exopolysaccharide
    )
  ) %>% rename(Dueholm = Exopolysaccharide) 
length(unique(Dueholm_BGCs$MAG))


epsSMASH_Dueholm <- fread("data/Dueholm/all_regions.tsv") %>% 
  mutate(
    product = case_when(
      str_detect(product, "cellulose") ~ "Cellulose",
      str_detect(product, "alginate") ~ "Alginate",
      str_detect(product, "pel") ~ "Pel",
      str_detect(product, "PNAG_eps") ~ "PNAG (eps)",
      str_detect(product, "PNAG-pga") ~ "PNAG (pga)",
      .default = product
    ),
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructan-sucrases|alpha-glucansucrases"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    )
  ) %>% 
  select(MAG = file, epsSMASH = product) %>%
  filter(epsSMASH %in% unique(Dueholm_BGCs$Dueholm)) %>% 
  full_join(
    Dueholm_BGCs %>% 
    group_by(MAG) %>% distinct(Dueholm, .keep_all = TRUE), by = c("MAG")
  ) %>%
  mutate(
  Dueholm = ifelse(Dueholm == epsSMASH | is.na(epsSMASH), Dueholm, NA),
  exoPS = ifelse(is.na(Dueholm), epsSMASH, Dueholm),
  `exoPS predictions` = case_when(
    is.na(Dueholm) & !is.na(epsSMASH) ~ "epsSMASH",
    !is.na(Dueholm) & is.na(epsSMASH) ~ "Dueholm et al. (2023)",
    !is.na(Dueholm) & !is.na(epsSMASH) ~ "Both",
    is.na(Dueholm) & is.na(epsSMASH) ~ "none"
    )
    )

ggplot(epsSMASH_Dueholm %>% group_by(`exoPS predictions`, exoPS) %>% count() %>%
  mutate(`exoPS predictions` = factor(`exoPS predictions`, levels = c("epsSMASH", "Dueholm et al. (2023)", "Both"))), 
  aes(x = exoPS, y = n, fill = `exoPS predictions`, label = n)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  scale_y_continuous(trans = "identity") +
  geom_bar_text(position = position_dodge2(preserve = "single"), outside = TRUE, size = 16) +
  ylab("BGCs") +
  scale_fill_brewer(palette =  "Set2") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 16),
    legend.text = element_text(size = 16)
  )
ggsave("figures/all/FigS2.svg", dpi = 300, height = 8, width = 12)

# get genomes in which Dueholm finds xanthan, psl or PNAG (eps)
Dueholm_wzxwzy <- Dueholm_BGCs %>% filter(str_detect("PNAG_eps|Psl|Xanthan", Dueholm)) %>% distinct(MAG)



epsSMASH_wzxwzy <- fread("data/Dueholm/all_regions.tsv") %>% 
  mutate(
    product = case_when(
      str_detect(product, "cellulose") ~ "Cellulose",
      str_detect(product, "alginate") ~ "Alginate",
      str_detect(product, "pel") ~ "Pel",
      str_detect(product, "PNAG") ~ "PNAG-pga",
      .default = product
    ),
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructan-sucrases|alpha-glucansucrases"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    )
  ) %>% 
  select(MAG = file, epsSMASH = product) %>%
  filter(MAG %in% Dueholm_wzxwzy$MAG)

length(unique(Dueholm_wzxwzy$MAG))

length(unique(epsSMASH_wzxwzy$MAG))
# we detect at least 1 putative wzx/wzy BGCs in the MAGs where Dueholm et al finds xanthan, psl or pnag (eps).
```

```{r}
gene_functions <- fread("data/gene_functions.tsv", header = FALSE) %>%
  rename(Query = V1, gene_function = V2)


data <- fread(
  "data/Dueholm/gene_info_MGP1000.tsv") %>%
  mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
  ungroup() %>%
  mutate(
      region_id = paste0(contig_id, ".", region_id),
      gene_id2 = paste0(genome_id, gene_id),
      location = as.character(location),
      location = gsub(":", "_", location),
      location = gsub("]", "_", location),
      location = gsub("\\[", "", location),
      location = gsub(">", "", location),
      location = gsub("<", "", location),
      location = gsub("join\\{", "", location),
      location = gsub("}", "", location),
      location = gsub(",.*", "", location)
  ) %>%
  group_by(gene_id2) %>%
  separate(`location`, c("start", "end", "strand"), sep = "_") %>%
  mutate(
      start = as.numeric(start),
      end = as.numeric(end),
      strand = ifelse(strand == "(+)", 1, -1)
  ) %>%
  left_join(gene_functions, by = c("Query" = "Query"))
   #filter(!str_detect(product, "-like"))

length(unique(data$genome_id))

# Function which plots all the selected gene clusters (every gene cluster in an order for example)
# The function takes a subset size as input, which is the number of gene clusters to plot in each plot
plot_gene_clusters <- function(data, subset_size) {
  # Get the unique regions
  unique_regions <- unique(data$region_id)
  
  # Calculate the number of subsets
  num_subsets <- ceiling(length(unique_regions) / subset_size)
  
  # Loop over each subset
  for(i in seq_len(num_subsets)) {
    # Calculate the indices for this subset
    start_index <- ((i - 1) * subset_size) + 1
    end_index <- min(i * subset_size, length(unique_regions))
    
    # Get the regions for this subset
    subset_regions <- unique_regions[start_index:end_index]
    
    # Filter the data for these regions and plot
    plot <- data %>%
      mutate(strand = ifelse(strand == 1, TRUE, FALSE)) %>%
      filter(region_id %in% subset_regions) %>%
      ggplot(aes(xmin = start, xmax = end, 
      y = Query, 
      fill = Query, forward = strand)) +
      geom_gene_arrow() +
      facet_wrap(~ region_id, scales = "free", ncol = 1) +
      ggtitle(paste("Gene clusters from subset", i, "of", num_subsets)) +
      theme(
        axis.text.y = element_text(angle=45),
        theme(legend.position="none")
      )
    print(plot)
  }
}

### Filtering and plotting gene clusters
filter_pel <- data %>%
  filter(str_detect(product, "pel")) %>% filter(genome_id %ni% Dueholm_BGCs$MAG) %>% filter(str_detect(Query, "pel")) 
  
length(unique(filter_pel$region_id))
plot_gene_clusters(filter_pel, 10)

filter_PNAG <- data %>%
  filter(str_detect(product, "PNAG")) %>% filter(genome_id %ni% Dueholm_BGCs$MAG)
  
length(unique(filter_PNAG$region_id))
plot_gene_clusters(filter_PNAG, 10)


filter_cellulose <- data %>%
  filter(str_detect(product, "cellulose")) %>% filter(genome_id %ni% Dueholm_BGCs$MAG) %>% filter(str_detect(Query, "Bcs"))
  
length(unique(filter_cellulose$region_id))
plot_gene_clusters(filter_cellulose, 10)


filter_lactobacillus <- data %>%
  filter(str_detect(product, "lactobacillus")) %>% filter(genome_id %ni% Dueholm_BGCs$MAG) %>% filter(str_detect(Query, "lactobacillus"))
  
length(unique(filter_lactobacillus$region_id))
plot_gene_clusters(filter_lactobacillus, 10)


```


