```{r setup, include=FALSE}
library(tidyverse)
library(igraph)
library(stringr)
library(ggforce)
library(data.table)
library(ggupset)
library(gggenes)
library(forcats)
library(readxl)
`%ni%` <- Negate(`%in%`)
```
Pel-positive or pel-like BGCs are found in all 161 genomes
```{r}

Results <- fread("../epsSMASH_analyses/Whitfield_Pel-positive/all_regions.tsv") %>% 
  separate_longer_delim(product, delim = " / ") %>%
  select(genome_id = file, tax = record_desc)

length(unique(Results$file))

BGC <- fread(
    "../epsSMASH_analyses/Whitfield_Pel-positive/gene_info_Whitfield.tsv") %>%
    mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
    mutate(genome_id = gsub("..//Whitfield_Pel-positive/antismash/", "", genome_id)) %>%
    group_by(gene_id) %>%
    filter(bitscore == max(bitscore)) %>%
    distinct(gene_id, .keep_all = TRUE) %>%
    ungroup() %>%
    mutate(
        region_id = paste0(genome_id, "_", contig_id, "_", region_id),
        location = as.character(location),
        location = gsub(":", "_", location),
        location = gsub("]", "_", location),
        location = gsub("\\[", "", location),
        location = gsub(">", "", location),
        location = gsub("<", "", location)
    ) %>%
    separate(`location`, c("start", "end", "strand"), sep = "_") %>%
    mutate(
        start = as.numeric(start),
        end = as.numeric(end),
        strand = ifelse(strand == "(+)", 1, -1)
    )

```

```{r}
# Function which plots all the selected gene clusters (every gene cluster in an order for example)
# The function takes a subset size as input, which is the number of gene clusters to plot in each plot
plot_gene_clusters <- function(data, subset_size) {
  # Get the unique regions
  unique_regions <- unique(data$region_id)
  
  # Calculate the number of subsets
  num_subsets <- ceiling(length(unique_regions) / subset_size)
  
  # Loop over each subset
  for(i in seq_len(num_subsets)) {
    # Calculate the indices for this subset
    start_index <- ((i - 1) * subset_size) + 1
    end_index <- min(i * subset_size, length(unique_regions))
    
    # Get the regions for this subset
    subset_regions <- unique_regions[start_index:end_index]
    
    # Filter the data for these regions and plot
    plot <- data %>%
      mutate(strand = ifelse(strand == 1, TRUE, FALSE)) %>%
      filter(region_id %in% subset_regions) %>%
      ggplot(aes(xmin = start, xmax = end, 
      y = "", 
      fill = Query, forward = strand)) +
      geom_gene_arrow() +
      facet_wrap(~ region_id, scales = "free", ncol = 2) +
      scale_fill_brewer(palette = "Set3") + ggtitle(paste("Gene clusters from subset", i, "of", num_subsets))
    print(plot)
  }
}

### Filtering and plotting gene clusters
filter <- BGC %>%
  filter(grepl("pel-like", product, ignore.case = TRUE)) #%>% filter(grepl("Run-SP154", tax_midas_v5.3))
  
length(unique(filter$region_id))
plot_gene_clusters(filter, 10)
```


