```{r setup, include=FALSE}
library(tidyverse)
library(igraph)
library(stringr)
library(ggforce)
library(data.table)
library(ggupset)
library(gggenes)
library(forcats)
library(ggtree)
library(treeio)
`%ni%` <- Negate(`%in%`)

gene_functions <- fread("data/gene_functions.tsv") 

# Function which plots all the selected gene clusters (every gene cluster in an order for example)
# The function takes a subset size as input, which is the number of gene clusters to plot in each plot
plot_gene_clusters <- function(data, subset_size, ncol = 2, legend_position = "right") {
  # Get the unique regions
  unique_regions <- unique(data$region_id)
  
  # Calculate the number of subsets
  num_subsets <- ceiling(length(unique_regions) / subset_size)
  
  # Loop over each subset
  for(i in seq_len(num_subsets)) {
    # Calculate the indices for this subset
    start_index <- ((i - 1) * subset_size) + 1
    end_index <- min(i * subset_size, length(unique_regions))
    
    # Get the regions for this subset
    subset_regions <- unique_regions[start_index:end_index]
    
    # Filter the data for these regions and plot
    plot <- data %>%
      mutate(strand = ifelse(strand == 1, TRUE, FALSE)) %>%
      filter(region_id %in% subset_regions) %>%
      ggplot(aes(xmin = start, xmax = end, 
      y = "", 
      fill = Query, forward = strand)) +
      geom_gene_arrow() +
      facet_wrap(~ region_id, scales = "free", ncol = ncol) +
      ggtitle(paste("Gene clusters from subset", i, "of", num_subsets)) +
      theme(legend.position = legend_position)
    print(plot)
  }
}


```
# MFD
```{r}

MFD_all_tax_derep <- fread("data/MFD/MFD_mags_drep_V4.tsv") %>% 
  select(genome_id = bin, gtdb_classification, MAG_status)  %>%
  mutate(Database = "MFD")

MFD_all_regions <- fread("../epsSMASH_analyses/MFD/data/epsSMASH_results/all_regions.tsv") %>%
  rename(genome_id = file) %>%
  separate_longer_delim(product, delim = " / ") %>%
  mutate(
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructansucrase|alpha-glucansucrase"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    ),
    product = case_when(
      product == "acetylated-cellulose" ~ "cellulose-acetylated",
      product == "type-1-cellulose" ~ "cellulose-type-1",
      product == "type-2-cellulose" ~ "cellulose-type-2",
      product == "type-3-cellulose" ~ "cellulose-type-3",
      product == "generic-cellulose" ~"cellulose-generic",
      .default = product
    )
    ) %>% left_join(MFD_all_tax_derep, by = c("genome_id")) %>%
  mutate(identifier = paste0(genome_id, "_", record_id,".region00", region)) %>%
  mutate(identifier = case_when(
    identifier == "MFD03250.bin.1.114_contig_1610.region0012" ~ "MFD03250.bin.1.114_contig_1610.region012",
    identifier == "MFD03250.bin.1.114_contig_1610.region0011" ~ "MFD03250.bin.1.114_contig_1610.region011",
    identifier == "MFD03250.bin.1.114_contig_1610.region0010" ~ "MFD03250.bin.1.114_contig_1610.region010",
    .default = identifier
  ))

MFD_all_regions_derep_HQ = MFD_all_regions %>% filter(genome_id %in% MFD_all_tax_derep$genome_id, MAG_status == "HQ")


MFD_all_regions_new <- fread("../epsSMASH_analyses/MFD/data/epsSMASH_results/all_regions.tsv") %>%
  rename(genome_id = file) %>%
  separate_longer_delim(product, delim = " / ") %>%
  mutate(
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructansucrase|alpha-glucansucrase"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    ),
    product = case_when(
      product == "acetylated-cellulose" ~ "cellulose-acetylated",
      product == "type-1-cellulose" ~ "cellulose-type-1",
      product == "type-2-cellulose" ~ "cellulose-type-2",
      product == "type-3-cellulose" ~ "cellulose-type-3",
      product == "generic-cellulose" ~"cellulose-generic",
      .default = product
    )
    ) %>% left_join(MFD_all_tax_derep, by = c("genome_id")) %>%
  mutate(identifier = paste0(genome_id, "_", record_id,".region00", region)) %>%
  mutate(identifier = case_when(
    identifier == "MFD03250.bin.1.114_contig_1610.region0012" ~ "MFD03250.bin.1.114_contig_1610.region012",
    identifier == "MFD03250.bin.1.114_contig_1610.region0011" ~ "MFD03250.bin.1.114_contig_1610.region011",
    identifier == "MFD03250.bin.1.114_contig_1610.region0010" ~ "MFD03250.bin.1.114_contig_1610.region010",
    .default = identifier
  ))


data <- fread(
    "../epsSMASH_analyses/MFD/data/gene_info_MFD.tsv", sep = "\t") %>%
    mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
    ungroup() %>%
    mutate(
        region_id = paste0(genome_id, "_", contig_id, ".", region_id),
        location = as.character(location),
        location = gsub(":", "_", location),
        location = gsub("]", "_", location),
        location = gsub("\\[", "", location),
        location = gsub(">", "", location),
        location = gsub("<", "", location),
        identifier = region_id
    ) %>%
  filter(identifier %in% new_clusters$identifier) %>%
  group_by(identifier, gene_id) %>%
  filter(bitscore == max(bitscore)) %>%
  distinct(gene_id, .keep_all = TRUE) %>%
  separate(`location`, c("start", "end", "strand"), sep = "_") %>%
  mutate(
      start = as.numeric(start),
      end = as.numeric(end),
      strand = ifelse(strand == "(+)", 1, -1)
  ) %>%
  left_join(gene_functions, by = c("Query" = "Query")) %>%
  left_join(MFD_all_tax_derep)
  

length(unique(data$identifier))




```
## plot 
```{r}
clusters <- data %>% filter(product == "ABC_dependent_putative_NO_OPX")
random_list <- sample(clusters$identifier, 80)

plot_gene_clusters(clusters %>% filter(!is.na(`e-value`)), 10)

```



# MiDAS

```{r}

MiDAS_HQ_tax <- fread("data/MiDAS/22K-hqMAGs.GTDB_midas.taxa.tsv") %>%
  select(genome_id = bin, gtdb_classification = tax_gtdb.r220, MiDAS_classification = "tax_midas_v5.3") %>%
  mutate(MAG_status = "HQ")

MiDAS_MQ_MiDAS <- fread("data/MiDAS/midas.mq.mags.midas5.3.taxa.tsv") %>%
  select(genome_id = V1, MiDAS_classification = V2) %>%
  mutate(MAG_status = "MQ")

MiDAS_MQ_tax <- fread("data/MiDAS/31K-mqMAGs.GTDB_taxa.tsv") %>%
  select(genome_id = bin, gtdb_classification = tax_gtdb.r220) %>% left_join(MiDAS_MQ_MiDAS)

MiDAS_all_tax <- rbind(MiDAS_HQ_tax, MiDAS_MQ_tax)  %>%
  mutate(Database = "MiDAS Global")

MiDAS_all_regions_derep <- fread("../epsSMASH_analyses/MiDAS/data/epsSMASH_results/all_regions.tsv") %>%
  rename(genome_id = file) %>%
  separate_longer_delim(product, delim = " / ") %>%
  mutate(
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructansucrase|alpha-glucansucrase"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    ),
    product = case_when(
      product == "acetylated-cellulose" ~ "cellulose-acetylated",
      product == "type-1-cellulose" ~ "cellulose-type-1",
      product == "type-2-cellulose" ~ "cellulose-type-2",
      product == "type-3-cellulose" ~ "cellulose-type-3",
      product == "generic-cellulose" ~"cellulose-generic",
      .default = product
    )
    ) %>% left_join(MiDAS_all_tax, by = c("genome_id")) %>%
  mutate(
    HQ = ifelse(
      genome_id %in% MiDAS_HQ_tax$genome_id, TRUE, FALSE
    )
  )  %>%
  mutate(identifier = paste0(genome_id, "_", record_id,".region00", region)) %>%
  mutate(identifier = case_when(
    identifier == "MFD03250.bin.1.114_contig_1610.region0012" ~ "MFD03250.bin.1.114_contig_1610.region012",
    identifier == "MFD03250.bin.1.114_contig_1610.region0011" ~ "MFD03250.bin.1.114_contig_1610.region011",
    identifier == "MFD03250.bin.1.114_contig_1610.region0010" ~ "MFD03250.bin.1.114_contig_1610.region010",
    .default = identifier
  )) %>%
  separate(gtdb_classification, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ";")


# List of dereplicated MiDAS genomes
MiDAS_derep <- fread("data/MiDAS/derep_MAGs_list.tsv")

# epsSMASH results for all dereplicated + HQ MiDAS global MAGs
MiDAS_all_regions_derep_HQ <- MiDAS_all_regions_derep %>% filter(MAG_status == "HQ")

# Taxonomy of all dereplicated MiDAS global MAGs
MiDAS_tax_derep <- MiDAS_all_tax %>% filter(genome_id %in% MiDAS_derep$genome_id) %>% mutate(Database = "MiDAS Global") %>% select(genome_id, gtdb_classification, MiDAS_classification, Database, MAG_status)

# Taxonomy of all dereplicated and HQ MiDAS global MAGs
MiDAS_tax_derep_HQ <- MiDAS_all_tax %>% filter(genome_id %in% MiDAS_derep$genome_id & genome_id %in% MiDAS_HQ_tax$genome_id) %>% mutate(Database = "MiDAS Global") %>% select(genome_id, gtdb_classification, MiDAS_classification, Database, MAG_status)



data <- fread(
    "../epsSMASH_analyses/MiDAS/data/gene_info_MiDAS.tsv", sep = "\t") %>%
    mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
    ungroup() %>%
    mutate(
        region_id = paste0(contig_id, ".", region_id),
        location = as.character(location),
        location = gsub(":", "_", location),
        location = gsub("]", "_", location),
        location = gsub("\\[", "", location),
        location = gsub(">", "", location),
        location = gsub("<", "", location),
        identifier = region_id
    ) %>%
  group_by(identifier, gene_id) %>%
  filter(bitscore == max(bitscore)) %>%
  distinct(gene_id, .keep_all = TRUE) %>%
  separate(`location`, c("start", "end", "strand"), sep = "_") %>%
  mutate(
      start = as.numeric(start),
      end = as.numeric(end),
      strand = ifelse(strand == "(+)", 1, -1)
  ) %>%
  left_join(gene_functions, by = c("Query" = "Query")) %>%
  left_join(MiDAS_tax_derep_HQ %>% select(genome_id, gtdb_classification))
  

length(unique(data$identifier))


other_phyla_pel <- data %>% filter(str_detect(product, "pel"))

plot_gene_clusters(other_phyla_pel %>% filter(str_detect(gtdb_classification, "o__Verrucomicrobiales")), 10)

```
## Sphingomonadaceae
## plot 
```{r}
regions <- c(
  "099-UY-16.bin.1.78_contig_1883",
  "099-UY-16.bin.1.31_contig_35780",
  "099-UY-16.bin.1.292_contig_2969",
  "099-UY-16.bin.1.230_contig_44951",
  "099-UY-16.bin.1.104_contig_2982",
  "095-US2-13.bin.1.198_contig_4565",
  "094-US2-01.bin.1.206_contig_160881",
  "092-US1-44.bin.1.172_contig_5654",
  "090-US1-124.bin.1.385_contig_7085",
  "090-US1-124.bin.1.320_contig_53019",
  "090-US1-124.bin.1.255_contig_45513",
  "090-US1-124.bin.1.128_contig_19462",
  "089-SG-01.bin.1.137_contig_39005",
  "077-MX-09.bin.1.99_contig_88290",
  "077-MX-09.bin.1.440_contig_84455",
  "020-NO1-03.bin.1.445_contig_50593",
  "020-NO1-03.bin.1.243_contig_14724",
  "020-NO1-03.bin.1.121_contig_6503",
  "016-PL-06.bin.1.536_contig_188",
  "015-DE-14.bin.1.526_contig_114256",
  "013-IT-11.bin.1.124_contig_8646",
  "009-AU-01.bin.1.204_contig_14633",
  "008-AR-23.bin.2.134_contig_17332",
  "008-AR-23.bin.1.656_contig_6080",
  "008-AR-23.bin.1.235_contig_1452",
  "008-AR-23.bin.1.174_contig_35722",
  "008-AR-23.bin.1.118_contig_30118",
  "006-MY-06.bin.1.936_contig_43031",
  "006-MY-06.bin.1.667_contig_19081",
  "006-MY-06.bin.1.398_contig_19088",
  "006-MY-06.bin.1.376_contig_169282",
  "004-NL-18.bin.1.334_contig_30312",
  "003-CA-05.bin.1.55_contig_5781",
  "003-CA-05.bin.1.382_contig_49931",
  "003-CA-05.bin.1.33_contig_53104",
  "003-CA-05.bin.1.16_contig_139895"
)
clusters <- data %>% filter(contig_id %in% regions)
length(unique(clusters$identifier))
random_list <- sample(clusters$identifier, 80)

plot_gene_clusters(clusters, 10)
```
# HumGut

```{r}

### HumGut and GOMC were using an old GTDB version, so we updated that:
GOMC_HumGut_tax <- fread("data/GTDB220_HumGut_GOMC/gtdbtk-v2.4.0_GOMC-HumGut.summary.tsv") %>% rename(genome_id = user_genome, gtdb_classification = classification)

HumGut_tax <- fread("data/HumGut/HumGut.tsv") %>%
    mutate(genome_file = gsub(".fna.gz", "", genome_file)) %>%
    select(genome_id = genome_file, OLD_gtdb_classification = gtdbtk_taxonomy, 
           gtdbtk_organism_name, ncbi_organism_name, `Contamination (%)` = contamination, 
          `Completeness (%)` = completeness,     cluster95) %>%
    mutate(Database = "HumGut") %>%
    left_join(GOMC_HumGut_tax, by = "genome_id")

# Due to how HumGut asks you to filter for the species representatives at 95% ANI (https://github.com/larssnip/HumGut/blob/main/README.md), it matters that you 
#derep before you filter for HQ species if you want only the ones designated as species reps. This results in about 200 less MAGs though.
HumGut_tax_HQ_derep <- HumGut_tax %>% distinct(cluster95, .keep_all = TRUE) %>% mutate(Database = "HumGut") %>% filter(`Contamination (%)` <= 5 & `Completeness (%)` >= 90) %>% mutate(MAG_status = "HQ")


HumGut_all_regions <- fread("data/HumGut/all_regions.tsv") %>%
  rename(genome_id = file) %>%
  mutate(
    Category = ifelse(
      str_detect(product,
        "putative_wzy_dependent|putative_wzy_dependent_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "putative_ABC_dependent|putative_ABC_dependent_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "putative_ABC_or_wzy_dependent"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructansucrase|alpha-glucansucrase"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    ),
    product = case_when(
      product == "acetylated-cellulose" ~ "cellulose-acetylated",
      product == "type-1-cellulose" ~ "cellulose-type-1",
      product == "type-2-cellulose" ~ "cellulose-type-2",
      product == "type-3-cellulose" ~ "cellulose-type-3",
      product == "generic-cellulose" ~"cellulose-generic",
      .default = product
    ),
    MAG_status = "HQ"
    ) %>% left_join(HumGut_tax_HQ_derep, by = c("genome_id")) 


data <- fread(
    "../epsSMASH_analyses/HumGut/data/gene_info_HumGut", sep = "\t") %>%
    mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
    ungroup() %>%
    mutate(
        region_id = paste0(contig_id, ".", region_id),
        location = as.character(location),
        location = gsub(":", "_", location),
        location = gsub("]", "_", location),
        location = gsub("\\[", "", location),
        location = gsub(">", "", location),
        location = gsub("<", "", location),
        identifier = region_id
    ) %>%
  group_by(identifier, gene_id) %>%
  filter(bitscore == max(bitscore)) %>%
  distinct(gene_id, .keep_all = TRUE) %>%
  separate(`location`, c("start", "end", "strand"), sep = "_") %>%
  mutate(
      start = as.numeric(start),
      end = as.numeric(end),
      strand = ifelse(strand == "(+)", 1, -1)
  ) %>%
  left_join(gene_functions, by = c("Query" = "Query")) %>%
  left_join(HumGut_tax_HQ_derep %>% select(genome_id, gtdb_classification))

x <- data %>% filter(region_id == "krakentaxid3029303HumGut_29303_1.region002")
  
plot_gene_clusters(data %>% filter(region_id == "krakentaxid3023692HumGut_23692_18.region001"), 2)

```
# GOMC

```{r}
GOMC_metadata <- fread("data/GOMC/41586_2024_7891_MOESM3_ESM.csv")
GOMC_HQ_genome_ids <- GOMC_metadata %>% filter(`Contamination (%)` <= 5, `Completeness (%)` >= 90) %>% rename(genome_id = Bin_id)


############################################################
# Load in GOMC epsSMASH results, add taxonomy and metadata #
############################################################

GOMC_metadata_derep <- fread("../epsSMASH_analyses/GOMC/data/41586_2024_7891_MOESM3_ESM.csv") %>% 
  rename(genome_id = Bin_id) %>%
  mutate(
    MAG_status = ifelse(`Contamination (%)` <= 5 & `Completeness (%)` >= 90, "HQ", "MQ")
      ) %>%
  select(genome_id, MAG_status)

GOMC_HumGut_tax_derep_HQ <- fread("data/GTDB220_HumGut_GOMC/gtdbtk-v2.4.0_GOMC-HumGut.summary.tsv") %>% rename(genome_id = user_genome, gtdb_classification = classification) %>% right_join(GOMC_metadata_derep) %>% 
  filter(MAG_status == "HQ")
  

GOMC_all_regions <- fread("data/GOMC/all_regions.tsv") %>%
  rename(genome_id = file) %>%
  separate_longer_delim(product, delim = " / ") %>%
  mutate(
    Category = ifelse(
      str_detect(product,
        "putative_wzy_dependent|putative_wzy_dependent_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "putative_ABC_dependent|putative_ABC_dependent_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "putative_ABC_or_wzy_dependent"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructansucrase|alpha-glucansucrase"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    ),
    product = case_when(
      product == "acetylated-cellulose" ~ "cellulose-acetylated",
      product == "type-1-cellulose" ~ "cellulose-type-1",
      product == "type-2-cellulose" ~ "cellulose-type-2",
      product == "type-3-cellulose" ~ "cellulose-type-3",
      product == "generic-cellulose" ~"cellulose-generic",
      .default = product
    ),
    MAG_status = "HQ"
    ) %>% left_join(GOMC_HumGut_tax_derep_HQ, by = c("genome_id"))

data <- fread(
    "../epsSMASH_analyses/GOMC/data/gene_info_GOMC.tsv", sep = "\t") %>%
    mutate(bitscore = ifelse(is.na(bitscore), 0, bitscore)) %>%
    ungroup() %>%
    mutate(
        region_id = paste0(contig_id, ".", region_id),
        location = as.character(location),
        location = gsub(":", "_", location),
        location = gsub("]", "_", location),
        location = gsub("\\[", "", location),
        location = gsub(">", "", location),
        location = gsub("<", "", location),
        identifier = region_id
    ) %>%
  group_by(identifier, gene_id) %>%
  filter(bitscore == max(bitscore)) %>%
  distinct(gene_id, .keep_all = TRUE) %>%
  separate(`location`, c("start", "end", "strand"), sep = "_") %>%
  mutate(
      start = as.numeric(start),
      end = as.numeric(end),
      strand = ifelse(strand == "(+)", 1, -1)
  ) %>%
  left_join(gene_functions, by = c("Query" = "Query")) %>%
  left_join(GOMC_HumGut_tax_derep_HQ %>% select(genome_id, gtdb_classification))

campylo <- data %>% filter(product == "cellulose" | product == "cellulose-like") %>% filter(str_detect(gtdb_classification, "c__Cyanobacteriia"))

plot_gene_clusters(campylo, 10)

```



