```{r setup, include=FALSE}
library(tidyverse)
library(igraph)
library(stringr)
library(ggforce)
library(data.table)
library(ggupset)
library(gggenes)
library(forcats)
library(ape)
library(RColorBrewer)
library(svglite)
library(aplot)
library(ggh4x)
library(treeio)
library(ggtree)
library(ggtreeExtra)
library(readxl)
library(patchwork)
library(RColorBrewer)

f <- function(pal) brewer.pal(brewer.pal.info[pal, "maxcolors"], pal)
(cols <- f("Set2"))

scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = (cols <- f("Set2")))
} 
`%ni%` <- Negate(`%in%`)
```

# SPMP
```{r}

SPMP_contig_stats_short_read <- fread("../data/SPMP/contig_stats_short_read.tsv") %>% 
  mutate(file = gsub(".fa", "", genome)) %>%
  select(file, length) %>%
  group_by(file) %>%
  reframe(
    decreasing_csizes = sort(length, decreasing = TRUE),
    tmp = cumsum(as.numeric(decreasing_csizes)),
    total_size = tmp[length(tmp)],
    N50 = decreasing_csizes[which(tmp >= total_size/2)[1]],
    `N50 (kbp)` = N50/1000
  ) %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`)
  

epsSMASH_shortread <- fread("../data/SPMP/all_regions_shortread.tsv")

# Read supplementary file from SPMP study (must be added to directory)
SPMP_shortread <- readxl::read_excel("../data/SPMP/41467_2022_33782_MOESM6_ESM.xlsx", sheet = 1) %>% select(file = 1,2,3,4) %>%
    mutate(
    MAG_status = ifelse(`Completeness (%)` >= 90 & `Contamination (%)` <= 5, "HQ", "MQ"),
    sequencing = "Short-read"
    ) %>% 
  group_by(MAG_status, sequencing) %>%
  mutate(MAGs_no = n()) %>%
  left_join(SPMP_contig_stats_short_read) %>%
  left_join(epsSMASH_shortread)

  
SPMP_contig_stats_hybrid <- fread("../data/SPMP/contig_stats_hybrid.tsv") %>% 
  mutate(file = gsub(".fasta", "", genome)) %>%
  select(file, length) %>%
  group_by(file) %>%
  reframe(
    decreasing_csizes = sort(length, decreasing = TRUE),
    tmp = cumsum(as.numeric(decreasing_csizes)),
    total_size = tmp[length(tmp)],
    N50 = decreasing_csizes[which(tmp >= total_size/2)[1]],
    `N50 (kbp)` = N50/1000
  ) %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`) %>% 
  mutate(file = gsub("TLL", "SPMP", file))

epsSMASH_hybrid <- fread("../data/SPMP/all_regions_hybrid.tsv") %>% 
  mutate(file = gsub("TLL", "SPMP", file))

# Read supplementary file from SPMP study (must be added to directory)
SPMP_hybrid <- readxl::read_excel("../data/SPMP/41467_2022_33782_MOESM6_ESM.xlsx", sheet = 2) %>% select(file = 1,2,3,4) %>%
    mutate(
    MAG_status = ifelse(`Completeness (%)` >= 90 & `Contamination (%)` <= 5, "HQ", "MQ"),
    sequencing = "Hybrid"
    ) %>% 
  group_by(MAG_status, sequencing) %>%
  mutate(MAGs_no = n()) %>%
  left_join(SPMP_contig_stats_hybrid) %>%
  left_join(epsSMASH_hybrid)


# Create base dataframe with common transformations
base_df_SPMP <- rbind(SPMP_shortread, SPMP_hybrid) %>%
  mutate(
    BGC_length = as.integer(end - start),
    Complete = !contig_edge,
    identifier = paste(file, sequencing, MAG_status)
  ) %>%
  unite(col = "sequencing+quality", c("sequencing", "MAG_status"), sep = ", ") %>%
  unite(col = "sequencing+quality", c("sequencing+quality", "MAGs_no"), sep = "\n n = ")

# Calculate percentage complete BGCs
epsSMASH_SPMP_perc <- base_df_SPMP %>%
  filter(!is.na(Complete)) %>% # Only look at BGCs, not all MAGs
  group_by(`sequencing+quality`) %>%
  summarise(`% complete exoPS BGCs` = round(mean(Complete), 5) * 100, .groups = "drop")

# Calculate exoPS BGCs for all sequencing/quality combinations in one operation

epsSMASH_SPMP_BGCs <- base_df_SPMP %>%
      group_by(file, `sequencing+quality`) %>%
      mutate(BGCs = ifelse(is.na(Complete), 0, n())) %>%
      group_by(`sequencing+quality`) %>%
      distinct(file, .keep_all = TRUE) %>%
      mutate(MAGs_no = n())

# Dataframe for N50 boxplots
epsSMASH_SPMP_N50 <- base_df_SPMP %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`, `sequencing+quality`)

```

# Eisenhofer et al.

```{r}

# Read supplementary file from Eisenhofer study (must be added to directory)
Eisenhofer_contig_stats <- fread("../data/Eisenhofer/genomeInformation.csv") %>% 
  mutate(file = gsub(".fa.gz", "", genome)) %>%
  select(file, N50) %>%
  mutate(`N50 (kbp)`  = N50/1000)
  

epsSMASH_Eisenhofer <- fread("../data/Eisenhofer/all_regions.tsv", sep = "\t") %>% 
  mutate(
    BGC_length = as.integer(end-start),
    Complete = ifelse(contig_edge == FALSE, TRUE, FALSE),
    Sample = gsub(".bin.*", "", file),
  ) 

Eisenhofer <- fread("../data/Eisenhofer/genomeInformation.csv") %>% mutate(
  sequencing = case_when(
      str_detect(genome, "Hybrid") ~ "Hybrid",
      str_detect(genome, "hifiasm") ~ "Long-read",
      str_detect(genome, "subsampled_20Gb") ~ "Short-read",
      str_detect(genome, "subsampled_40Gb") ~ "Short-read",
    ),
    genome = gsub(".fa.gz", "", genome),
    MAG_status = ifelse(`completeness` >= 90 & `contamination` <= 5, "HQ", "MQ"),
    MAG_status = ifelse(`completeness` >= 90 & `contamination` <= 5, "HQ", "MQ")
  ) %>% rename(file = genome) %>%
  group_by(MAG_status, sequencing) %>%
  mutate(MAGs_no = n()) %>%
  left_join(Eisenhofer_contig_stats) %>%
  left_join(epsSMASH_Eisenhofer)
  



# Create base dataframe with common transformations
base_df_Eisenhofer <- Eisenhofer %>%
  mutate(
    BGC_length = as.integer(end - start),
    Complete = !contig_edge,
    identifier = paste(file, sequencing, MAG_status)
  ) %>%
  unite(col = "sequencing+quality", c("sequencing", "MAG_status"), sep = ", ") %>%
  unite(col = "sequencing+quality", c("sequencing+quality", "MAGs_no"), sep = "\n n = ")


# Calculate percentage complete BGCs
epsSMASH_Eisenhofer_perc <- base_df_Eisenhofer %>%
  filter(!is.na(Complete)) %>% # Only look at BGCs, not all MAGs
  group_by(`sequencing+quality`) %>%
  summarise(`% complete exoPS BGCs` = round(mean(Complete), 5) * 100, .groups = "drop")

# Calculate exoPS BGCs for all sequencing/quality combinations in one operation

epsSMASH_Eisenhofer_BGCs <- base_df_Eisenhofer %>%
      group_by(file, `sequencing+quality`) %>%
      mutate(BGCs = ifelse(is.na(Complete), 0, n())) %>%
      group_by(`sequencing+quality`) %>%
      distinct(file, .keep_all = TRUE) %>%
      mutate(MAGs_no = n())

# Dataframe for N50 boxplots
epsSMASH_Eisenhofer_N50 <- base_df_Eisenhofer %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`, `sequencing+quality`)

```


# MFD

```{r}


# Figuring out which samples are shared between the deep and shallow sequencing (They sequenced 10k samples for shallow sequencing and only 153 for deep sequencing)
# Dereplication was done on both the genome sets, so since we're subsetting the shallow MAGs to only the ones from samples where deep sequencing was also done, we are getting less than 153 shared samples (70 shared samples)

MFD_contig_stats_deep <- fread("../data/MFD/contig_stats.tsv") %>% 
  mutate(file = gsub(".fa", "", genome)) %>%
  select(file, length) %>%
  group_by(file) %>%
  reframe(
    decreasing_csizes = sort(length, decreasing = TRUE),
    tmp = cumsum(as.numeric(decreasing_csizes)),
    total_size = tmp[length(tmp)],
    N50 = decreasing_csizes[which(tmp >= total_size/2)[1]],
    `N50 (kbp)` = N50/1000
  ) %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`)

epsSMASH_MFD_deep <- fread("../data/MFD/all_regions_all_deep_MAGs.tsv")

# Read supplementary file from MFD long-read study (must be added to directory)
MFD_deep <- fread("../data/MFD/MFD_mags_drep_V4.tsv") %>% rename(file = bin) %>% mutate(Sample = gsub(".bin.*", "", file)) %>%
  mutate(
    sequencing = "Long-read"
    ) %>%
  group_by(MAG_status, sequencing) %>%
  mutate(MAGs_no = n()) %>%
  left_join(MFD_contig_stats_deep) %>%
  left_join(epsSMASH_MFD_deep)


MFD_lib <- fread("../data/MFD/MFD_lib.tsv", header = FALSE)

setnames(MFD_lib, c("Sample", "lib"))

# Read supplementary file from MFD study (must be added to directory)
MFD_contig_stats_shallow <- fread("../data/MFD/contig_stats_shallow.tsv") %>% 
  mutate(file = gsub(".fa", "", genome)) %>%
  select(file, length) %>%
  group_by(file) %>%
  reframe(
    decreasing_csizes = sort(length, decreasing = TRUE),
    tmp = cumsum(as.numeric(decreasing_csizes)),
    total_size = tmp[length(tmp)],
    N50 = decreasing_csizes[which(tmp >= total_size/2)[1]],
    `N50 (kbp)` = N50/1000
  ) %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`)

epsSMASH_MFD_shallow <- fread("../data/MFD/all_regions_shallow.tsv") %>% 
  mutate(lib = gsub("\\..*", "", file)) %>%
  left_join(MFD_lib) %>%
  filter(Sample %in% MFD_deep$Sample)


MFD_shallow <- fread("../data/MFD/mags_shallow_drep.tsv") %>% rename(file = bin) %>% 
  mutate(lib = gsub("\\..*", "", file)) %>%
  left_join(MFD_lib) %>%
  filter(Sample %in% MFD_deep$Sample) %>%
  mutate(
    MAG_status = ifelse(`Completeness_CheckM1` >= 90 & `Contamination_CheckM1` <= 5, "HQ", "MQ"),
    MAG_status = ifelse(`Completeness_CheckM2` >= 90 & `Contamination_CheckM2` <= 5, "HQ", "MQ"),
    sequencing = "Short-read"
  ) %>%
  group_by(MAG_status, sequencing) %>%
  mutate(MAGs_no = n()) %>%
  left_join(MFD_contig_stats_shallow) %>%
  left_join(epsSMASH_MFD_shallow)
  

# Create base dataframe with common transformations
base_df_MFD <- rbind(MFD_deep, MFD_shallow) %>%
  mutate(
    BGC_length = as.integer(end - start),
    Complete = !contig_edge,
    identifier = paste(file, sequencing, MAG_status)
  ) %>%
  unite(col = "sequencing+quality", c("sequencing", "MAG_status"), sep = ", ") %>%
  unite(col = "sequencing+quality", c("sequencing+quality", "MAGs_no"), sep = "\n n = ")


# Calculate percentage complete BGCs
epsSMASH_MFD_perc <- base_df_MFD %>%
  filter(!is.na(Complete)) %>% # Only look at BGCs, not all MAGs
  group_by(`sequencing+quality`) %>%
  summarise(`% complete exoPS BGCs` = round(mean(Complete), 5) * 100, .groups = "drop")

# Calculate exoPS BGCs for all sequencing/quality combinations in one operation

epsSMASH_MFD_BGCs <- base_df_MFD %>%
      group_by(file, `sequencing+quality`) %>%
      mutate(BGCs = ifelse(is.na(Complete), 0, n())) %>%
      group_by(`sequencing+quality`) %>%
      distinct(file, .keep_all = TRUE) %>%
      mutate(MAGs_no = n())

# Dataframe for N50 boxplots
epsSMASH_MFD_N50 <- base_df_MFD %>%
  distinct(file, .keep_all = TRUE) %>%
  select(file, `N50 (kbp)`, `sequencing+quality`)

```

### Plotting
```{r}

brewer.pal(6, "Paired")

#    "#FB9A99" "#E31A1C" "#B2DF8A" "#33A02C" "#A6CEE3" "#1F78B4"
myColors_SPMP <- c("#FB9A99", "#E31A1C", "#B2DF8A", "#33A02C")
myColors_Eisenhofer <- c("#FB9A99", "#E31A1C", "#B2DF8A", "#33A02C", "#A6CEE3", "#1F78B4")
myColors_MFD <- c("#FB9A99", "#E31A1C", "#A6CEE3", "#1F78B4")


names(myColors_SPMP) <- c("Short-read, MQ\n n = 1977", "Short-read, HQ\n n = 812", "Hybrid, MQ\n n = 2728", "Hybrid, HQ\n n = 1769")
names(myColors_Eisenhofer) <- c("Short-read, MQ\n n = 77", "Short-read, HQ\n n = 256", "Hybrid, MQ\n n = 37", "Hybrid, HQ\n n = 136", "Long-read, MQ\n n = 50", "Long-read, HQ\n n = 63")
names(myColors_MFD) <- c("Short-read, MQ\n n = 186", "Short-read, HQ\n n = 82", "Long-read, MQ\n n = 10746", "Long-read, HQ\n n = 4894")

# Function to create BGCs/MAG plots
create_BGCs_plot <- function(data, title_text, colors) {
  
  # Transform data
  plot_data <- data %>% 
    mutate(`sequencing+quality` = factor(`sequencing+quality`, levels=names(colors)))
  
  ggplot(plot_data, 
         aes(x = `sequencing+quality`, y = BGCs, fill = `sequencing+quality`)) +
    geom_jitter(shape=21, position=position_jitter(0.2), size = 3) +
    geom_boxplot(width=0.2, size = 0.75, fill = "gray", color = "black", outlier.shape = NA) +
    scale_y_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20), limits = c(0, 20)) +
    scale_fill_manual(name = "Sequencing and quality", values = colors, drop = FALSE) +
    scale_color_manual(name = "Sequencing and quality", values = colors, drop = FALSE) +
    ggtitle(title_text) +
    xlab("") +
    ylab("BGCs in MAGs") +
    theme_bw() +
    theme(
      axis.text.x = element_text(size = 12, angle = 60, hjust = 1),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size = 12),
      legend.position = "none",
      plot.title = element_text(size = 12, hjust = 0.5),
      panel.grid.major.x = element_blank(),
      legend.text=element_text(size=12),
      legend.title=element_text(size=12),
      axis.ticks.x = element_blank()
    )
}

# Function to create completeness plots
create_completeness_plot <- function(data, title_text, colors) {
  
  # Transform data
  plot_data <- data %>% 
    mutate(`sequencing+quality` = factor(`sequencing+quality`, levels=names(colors)))
  
  ggplot(plot_data, 
         aes(x = `sequencing+quality`, y = `% complete exoPS BGCs`, fill = `sequencing+quality`)) +
    geom_col(position = position_dodge2(width = 0.9), width = 0.8) +
    scale_fill_manual(name = "Sequencing and quality", values = colors, drop = FALSE) +
    scale_y_continuous(limits = c(0,100), expand = c(0,0)) +
    xlab("") +
    ylab("% complete BGCs") +
    theme_bw() +
    theme(
      axis.text.x = element_text(size = 12, angle = 60, hjust = 1),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size = 12),
      legend.position = "none",
      plot.title = element_text(size = 12, hjust = 0.5),
      panel.grid.major.x = element_blank(),
      legend.text=element_text(size=12),
      legend.title=element_text(size=12),
      axis.ticks.x = element_blank()
    )
}


# Function to create N50 plots
create_N50_plot <- function(data, title_text, colors) {
  
  # Transform data
  plot_data <- data %>% 
    mutate(`sequencing+quality` = factor(`sequencing+quality`, levels=names(colors)))
  
  ggplot(plot_data, 
         aes(x = `sequencing+quality`, y = `N50 (kbp)`, fill = `sequencing+quality`)) +
    geom_jitter(shape=21, position=position_jitter(0.2), size = 3) +
    geom_boxplot(width=0.2, size = 0.75, fill = "gray", color = "black", outlier.shape = NA) +
    scale_fill_manual(name = "Sequencing and quality", values = colors, drop = FALSE) +
    scale_y_continuous(trans = "log10", limits = c(10, 10000)) +
    xlab("") +
    theme_bw() +
    theme(
      axis.text.x = element_text(size = 12, angle = 60, hjust = 1),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size = 12),
      legend.position = "none",
      plot.title = element_text(size = 12, hjust = 0.5),
      panel.grid.major.x = element_blank(),
      legend.text=element_text(size=12),
      legend.title=element_text(size=12)
    )
}




# Create plots for each dataset
MFD_BGCs <- create_BGCs_plot(epsSMASH_MFD_BGCs, "Microflora Danica", myColors_MFD) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())

Eisenhofer_BGCs <- create_BGCs_plot(epsSMASH_Eisenhofer_BGCs, "Eisenhofer et al., 2024", myColors_Eisenhofer) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.y = element_blank())

SPMP_BGCs <- create_BGCs_plot(epsSMASH_SPMP_BGCs, "Singapore Platinum\nMetagenomes Project", myColors_SPMP) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.y = element_blank())

MFD_completeness <- create_completeness_plot(epsSMASH_MFD_perc, "Microflora Danica", myColors_MFD) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())

Eisenhofer_completeness <- create_completeness_plot(epsSMASH_Eisenhofer_perc, "Eisenhofer et al., 2024", myColors_Eisenhofer) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank())

SPMP_completeness <- create_completeness_plot(epsSMASH_SPMP_perc, "Singapore Platinum\nMetagenomes Project", myColors_SPMP) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank())

MFD_N50 <- create_N50_plot(epsSMASH_MFD_N50, "Microflora Danica", myColors_MFD)

SPMP_N50 <- create_N50_plot(epsSMASH_SPMP_N50, "Singapore Platinum\nMetagenomes Project", myColors_SPMP) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())

Eisenhofer_N50 <- create_N50_plot(epsSMASH_Eisenhofer_N50, "Eisenhofer et al., 2024", myColors_Eisenhofer) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())

# Combine all plots
top <- MFD_BGCs + SPMP_BGCs + Eisenhofer_BGCs + plot_layout(widths = c(1, 1, 1.5))
middle <- MFD_completeness + SPMP_completeness + Eisenhofer_completeness + plot_layout(widths = c(1, 1, 1.5))
bottom <- MFD_N50 + SPMP_N50 + Eisenhofer_N50 + plot_layout(widths = c(1, 1, 1.5))

# Display the plot
Fig2 <- top / middle / bottom
Fig2

ggsave("../figures/Fig2.svg", Fig2, dpi = 300, height = 10, width = 10)
```
