```{r setup, include=FALSE}
library(tidyverse)      
library(data.table)     
library(readxl)         
library(ggfittext)  
`%ni%` <- Negate(`%in%`)
```

```{r}
# Read supplementary file from Dueholm et al. study
Dueholm_BGCs <- fread("../data/Dueholm/Dueholm.tsv") %>% 
  group_by(MAG, Exopolysaccharide) %>% 
  mutate(
    Exopolysaccharide = case_when(
      str_detect(Exopolysaccharide, "Cellulose") ~ "Cellulose",
      Exopolysaccharide == "PNAG_pga" ~ "PNAG (pga)",
      Exopolysaccharide == "PNAG_eps" ~ "PNAG (eps)",
      .default = Exopolysaccharide
    )
  ) %>% rename(Dueholm = Exopolysaccharide) 
length(unique(Dueholm_BGCs$MAG))


epsSMASH_Dueholm <- fread("../data/Dueholm/all_regions.tsv") %>% 
  mutate(
    product = case_when(
      str_detect(product, "cellulose") ~ "Cellulose",
      str_detect(product, "alginate") ~ "Alginate",
      str_detect(product, "pel") ~ "Pel",
      str_detect(product, "PNAG_eps") ~ "PNAG (eps)",
      str_detect(product, "PNAG-pga") ~ "PNAG (pga)",
      .default = product
    ),
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructan-sucrases|alpha-glucansucrases"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    )
  ) %>% 
  select(MAG = file, epsSMASH = product) %>%
  filter(epsSMASH %in% unique(Dueholm_BGCs$Dueholm)) %>% 
  full_join(
    Dueholm_BGCs %>% 
    group_by(MAG) %>% distinct(Dueholm, .keep_all = TRUE), by = c("MAG")
  ) %>%
  mutate(
  Dueholm = ifelse(Dueholm == epsSMASH | is.na(epsSMASH), Dueholm, NA),
  exoPS = ifelse(is.na(Dueholm), epsSMASH, Dueholm),
  `exoPS predictions` = case_when(
    is.na(Dueholm) & !is.na(epsSMASH) ~ "epsSMASH",
    !is.na(Dueholm) & is.na(epsSMASH) ~ "Dueholm et al. (2023)",
    !is.na(Dueholm) & !is.na(epsSMASH) ~ "Both",
    is.na(Dueholm) & is.na(epsSMASH) ~ "none"
    )
    )

ggplot(epsSMASH_Dueholm %>% group_by(`exoPS predictions`, exoPS) %>% count() %>%
  mutate(`exoPS predictions` = factor(`exoPS predictions`, levels = c("epsSMASH", "Dueholm et al. (2023)", "Both"))), 
  aes(x = exoPS, y = n, fill = `exoPS predictions`, label = n)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  scale_y_continuous(trans = "identity") +
  geom_bar_text(position = position_dodge2(preserve = "single"), outside = TRUE, size = 16) +
  ylab("BGCs") +
  scale_fill_brewer(palette =  "Set2") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 16),
    legend.text = element_text(size = 16)
  )
ggsave("../figures/FigS2.svg", dpi = 300, height = 8, width = 12)

# get genomes in which Dueholm finds xanthan, psl or PNAG (eps)
Dueholm_wzxwzy <- Dueholm_BGCs %>% filter(str_detect("PNAG_eps|Psl|Xanthan", Dueholm)) %>% distinct(MAG)



epsSMASH_wzxwzy <- fread("../data/Dueholm/all_regions.tsv") %>% 
  mutate(
    product = case_when(
      str_detect(product, "cellulose") ~ "Cellulose",
      str_detect(product, "alginate") ~ "Alginate",
      str_detect(product, "pel") ~ "Pel",
      str_detect(product, "PNAG") ~ "PNAG-pga",
      .default = product
    ),
    Category = ifelse(
      str_detect(product,
        "wzy_dependent_putative|wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", "NA"
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_dependent_putative|ABC_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
        "ABC_wzy_dependent_putative|ABC_wzy_dependent_putative_NO_OPX"
      ), "Uncharacterised", Category
    ),
    Category = ifelse(
      str_detect(product,
      "amylovoran_stewartan|acetan|succinoglycan|colanic|xanthan|galactoglucan|psl|PNAG_eps|lactobacillus_eps|sphingans|zooglan|emulsan|PNAG_eps"
      ), "Wzx/Wzy", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "cellulose|pel-positive|pel|alginate|curdlan|PNAG-ica|PNAG-pga|HA_has"), "Synthase", Category
    ),
    Category = ifelse(
      str_detect(product, 
      "fructan-sucrases|alpha-glucansucrases"), "Sucrase", Category
    ),
    n_Category = case_when(
      Category == "Uncharacterised" ~ 1,
      Category == "Synthase" ~ 2,
      Category == "Wzx/Wzy" ~ 3,
      Category == "Sucrase" ~ 4
    )
  ) %>% 
  select(MAG = file, epsSMASH = product) %>%
  filter(MAG %in% Dueholm_wzxwzy$MAG)

length(unique(Dueholm_wzxwzy$MAG))

length(unique(epsSMASH_wzxwzy$MAG))
# we detect at least 1 putative wzx/wzy BGCs in the MAGs where Dueholm et al finds xanthan, psl or pnag (eps).
```